# -*- coding: utf-8 -*-
"""00.gains_table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E21WIEGlN1SJBY9-HSw1YaIiapG3t1a-
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use("ggplot")

"""# Import"""

df_credit = pd.read_csv("/content/drive/MyDrive/Portfolio_WL/Gains_table/behavior_sample_model_gain.csv")
df_credit

df_credit["fx_prob"]  = pd.qcut(df_credit["prob_rf"], 10, labels=False)

df_credit_agg = df_credit.groupby("fx_prob", observed=False).agg({"Target":"mean"}).reset_index()
df_credit_agg

fig = plt.subplots(figsize=(6, 5))
sns.lineplot(x = "fx_prob", y = "Target", data = df_credit_agg)